config/routes.rb
Rails.application.routes.draw do
  get "/", to: redirect("/admin")

  get "/login" => "auth0#login"
  get "/auth/auth0/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/auth/logout" => "auth0#logout"

  get "/admin" => "admin/base#welcome"

  namespace :admin do
    resources :teams
    resources :sponsors
    resources :news_articles
    resources :videos
    resource :publications, only: [:create]
  end

  resources :news_articles, only: [:index]
  resources :teams, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/news_article.rb
class NewsArticle < ApplicationRecord
  # Extensions
  has_rich_text :content
  has_one_attached :image

  def to_s
    title
  end
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  # Relationships
  belongs_to :team

  # Extensions
  has_one_attached :image

  def to_s
    name
  end
end

app/models/team.rb
class Team < ApplicationRecord
  # Relationships
  has_many :sponsors

  # Extensions
  has_one_attached :team_photo

  def to_s
    name
  end

  def players_as_paragraph
    players.join("\n")
  rescue
    nil
  end

  def players_as_paragraph=(text)
    self.players = text.split("\n")
  end
end

app/models/video.rb
class Video < ApplicationRecord
  def to_s
    name
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :user_check

  helper_method :model

  def welcome
  end

  def index
    @records = model.all
  end

  def new
    @record = model.new
  end

  def create
    @record = model.new(clean_params)
    @record.save!

    redirect_to action: "index", notice: "#{@record} was succcessfully created."
  end

  def edit
    @record = model.find(params[:id])
  end

  def update
    @record = model.find(params[:id])
    @record.attributes = clean_params
    @record.save!

    redirect_to action: "index", notice: "#{@record} was succcessfully updated."
  end

  private

  def user_check
    @user = session[:userinfo]
    if @user.nil?
      redirect_to "/login"
    end
  end
end

app/controllers/admin/news_articles_controller.rb
class Admin::NewsArticlesController < Admin::BaseController
  private

  def model
    NewsArticle
  end

  def clean_params
    params.require(:news_article).permit(:title, :author, :published_at, :content, :image)
  end
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < ApplicationController
  def create
    Faraday.post(publish_url) if Rails.env.production?
    redirect_to admin_path, notice: "Site has been scheduled to publish. This can take several minutes."
  end

  private

  def publish_url
    Rails.application.credentials.publish_url
  end
end

app/controllers/admin/sponsors_controller.rb
class Admin::SponsorsController < Admin::BaseController
  private

  def model
    Sponsor
  end

  def clean_params
    params.require(:sponsor).permit(:name, :url, :team_id, :image)
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < Admin::BaseController
  def index
    @records = Team.order(:slug).all
  end

  private

  def model
    Team
  end

  def clean_params
    params.require(:team).permit(:slug, :name, :manager_1_position, :manager_1_name, :manager_2_position, :manager_2_name, :manager_3_position, :manager_3_name, :manager_4_position, :manager_4_name, :fa_table_lrcode, :fa_table_division_season, :fa_fixture_lrcode, :fa_fixture_division_season, :players_as_paragraph, :team_photo, :twitter_handle)
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  private

  def model
    Video
  end

  def clean_params
    params.require(:video).permit(:name, :description, :youtube_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def login
  end

  def callback
    # OmniAuth stores the information returned from Auth0 and the IdP in request.env['omniauth.auth'].
    # In this code, you will pull the raw_info supplied from the id_token and assign it to the session.
    # Refer to https://github.com/auth0/omniauth-auth0/blob/master/EXAMPLES.md#example-of-the-resulting-authentication-hash for complete information on 'omniauth.auth' contents.
    auth_info = request.env["omniauth.auth"]
    session[:userinfo] = auth_info["extra"]["raw_info"]

    # Redirect to the URL you want after successful auth
    redirect_to "/admin"
  end

  def failure
    # Handles failed authentication -- Show a failure page (you can also handle with a redirect)
    @error_msg = request.params["message"]
  end

  def logout
    reset_session
    redirect_to logout_url, allow_other_host: true
  end

  private

  def logout_url
    request_params = {
      returnTo: admin_url,
      client_id: Rails.application.credentials.auth0[Rails.env].client_id
    }

    URI::HTTPS.build(host: Rails.application.credentials.auth0[Rails.env].domain, path: "/v2/logout", query: request_params.to_query).to_s
  end
end

app/controllers/news_articles_controller.rb
class NewsArticlesController < ApplicationController
  def index
    @news_articles = NewsArticle.all
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.order(:slug).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/base/edit.html.erb
<h1 class="text-xl font-semibold" >Edit <%= @record.class.model_name.human.titleize %>: <%= @record %></h1>

<%= form_for [:admin, @record], method: :put do |f| %>
  <%= render partial: "form", locals: { f: f } %>

  <div class="flex justify-end">
    <%= f.submit "Save", class: "btn btn-primary mt-4" %>
  </div>
<% end %>

app/views/admin/base/index.html.erb
<div class="flex justify-end">
  <%= link_to "New #{model.model_name.human.titleize}", url_for(action: "new"), class: "btn btn-primary mb-4" %>
</div>

<div class="overflow-x-auto">
  <table class="table w-full">
    <!-- head -->
    <thead>
      <%= render partial: "header" %>
    </thead>
    <tbody>
      <%= render partial: "row", collection: @records %>
    </tbody>
  </table>
</div>

app/views/admin/base/new.html.erb
<h1 class="text-xl font-semibold" >New <%= @record.class.model_name.human.titleize %></h1>

<%= form_for [:admin, @record], method: :post do |f| %>
  <%= render partial: "form", locals: { f: f } %>

  <div class="flex justify-end">
    <%= f.submit "Save", class: "btn btn-primary mt-4" %>
  </div>
<% end %>

app/views/admin/base/welcome.html.erb
<h1 class="text-xl font-semibold">Welcome to CCFC EJA Admin</h1>

app/views/admin/news_articles/_form.html.erb
<div class="my-3 flex flex-col">
  <%= f.label :title, "Title", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_field :title, class: "w-full lg:w-1/2" %>
</div>

<div class="my-3 flex flex-col">
  <%= f.label :author, "Author", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_field :author, class: "w-full lg:w-1/2" %>
</div>

<div class="my-3 flex flex-col">
  <%= f.label :published_at, "Publish Date", class: "uppercase text-xs font-light mb-1" %>
  <%= f.date_field :published_at, class: "w-full lg:w-1/2" %>
</div>

<div class="my-3 flex flex-col">
  <%= f.label :image, "Image", class: "uppercase text-xs font-light mb-1" %>
  <% if @record.image.present? %>
    <div class="avatar">
      <div class="w-32 rounded">
        <%= image_tag @record.image %>
      </div>
    </div>
  <% end %>
  <%= f.file_field :image, class: "file-input w-full lg:w-1/2" %>
</div>

<div class="mt-5 flex flex-col">
  <%= f.label :content, "Article Text", class: "uppercase text-xs font-light mb-1" %>
  <%= f.rich_text_area :content, class: "w-full h-96" %>
</div>

app/views/admin/news_articles/_header.html.erb
<th>Title</th>
<th>Author</th>
<th>Published</th>
<th>Actions</th>

app/views/admin/news_articles/_row.html.erb
<tr>
  <td><%= row.title %></td>
  <td><%= row.author %></td>
  <td><%= row.published_at %></td>
  <td>
    <%= link_to "Edit", edit_admin_news_article_path(row), class: "btn btn-primary btn-xs" %>
  </td>
</tr>

app/views/admin/sponsors/_form.html.erb
<div class="my-3 flex flex-col">
  <%= f.label :name, "Name", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_field :name, class: "w-full lg:w-1/2" %>
</div>

<div class="my-3 flex flex-col">
  <%= f.label :url, "Website Url", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_field :url, class: "w-full lg:w-1/2" %>
  <p class="text-gray-600 uppercase text-xs font-light mt-1">Start with http:// or https://</p>
</div>

<div class="my-3 flex flex-col w-1/2">
  <%= f.label :team_id, "Team", class: "uppercase text-xs font-light mb-1" %>
  <%= f.select :team_id, [["Please Select", nil]] + Team.all.pluck(:name, :id), class: "select w-full max-w-xs" %>
</div>

<div class="my-3 flex flex-col">
  <%= f.label :image, "Image", class: "uppercase text-xs font-light mb-1" %>
  <% if @record.image.present? %>
    <div class="avatar">
      <div class="w-32 rounded">
        <%= image_tag @record.image %>
      </div>
    </div>
  <% end %>
  <%= f.file_field :image, class: "file-input w-full lg:w-1/2" %>
</div>

app/views/admin/sponsors/_row.html.erb
<tr>
  <td><%= row.name %></td>
  <td>
    <%= link_to "Edit", edit_admin_sponsor_path(row), class: "btn btn-primary btn-xs" %>
  </td>
</tr>

app/views/admin/teams/_form.html.erb
<div class="my-3 flex flex-col">
  <%= f.label :slug, "Slug", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_field :slug, class: "w-full lg:w-1/4" %>
</div>

<div class="my-3 flex flex-col">
  <%= f.label :name, "Team Name", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_field :name, class: "w-full lg:w-1/2" %>
</div>

<div class="my-3 flex flex-col">
  <%= f.label :twitter_handle, "Twitter Handle", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_field :twitter_handle, class: "w-full lg:w-1/2" %>
</div>

<div class="card w-full bg-base-100 shadow-xl lg:w-3/4 mb-4">
  <div class="card-body">
    <h2 class="card-title">Managers</h2>

    <div class="my-3 flex flex-col">
      <%= f.label :manager_1_position, "Manager 1", class: "uppercase text-xs font-light mb-1" %>
      <div class="flex flex-row">
        <%= f.text_field :manager_1_position, placeholder: "Position", class: "w-1/2 lg:w-1/4 mr-2" %>
        <%= f.text_field :manager_1_name, placeholder: "Name", class: "w-1/2 lg:w-1/2" %>
      </div>
    </div>

    <div class="my-3 flex flex-col">
      <%= f.label :manager_2_position, "Manager 2", class: "uppercase text-xs font-light mb-1" %>
      <div class="flex flex-row">
        <%= f.text_field :manager_2_position, placeholder: "Position", class: "w-1/2 lg:w-1/4 mr-2" %>
        <%= f.text_field :manager_2_name, placeholder: "Name", class: "w-1/2 lg:w-1/2" %>
      </div>
    </div>

    <div class="my-3 flex flex-col">
      <%= f.label :manager_3_position, "Manager 3", class: "uppercase text-xs font-light mb-1" %>
      <div class="flex flex-row">
        <%= f.text_field :manager_3_position, placeholder: "Position", class: "w-1/2 lg:w-1/4 mr-2" %>
        <%= f.text_field :manager_3_name, placeholder: "Name", class: "w-1/2 lg:w-1/2" %>
      </div>
    </div>

    <div class="my-3 flex flex-col">
      <%= f.label :manager_4_position, "Manager 4", class: "uppercase text-xs font-light mb-1" %>
      <div class="flex flex-row">
        <%= f.text_field :manager_4_position, placeholder: "Position", class: "w-1/2 lg:w-1/4 mr-2" %>
        <%= f.text_field :manager_4_name, placeholder: "Name", class: "w-1/2 lg:w-1/2" %>
      </div>
    </div>
  </div>
</div>

<div class="card w-full bg-base-100 shadow-xl lg:w-3/4 mb-5">
  <div class="card-body">
    <h2 class="card-title">FA Full Time Codes</h2>

    <div class="my-3 flex flex-col">
      <%= f.label :fa_table_lrcode, "Table LR Code / Division Season", class: "uppercase text-xs font-light mb-1" %>
      <div class="flex flex-row">
        <%= f.text_field :fa_table_lrcode, placeholder: "LR Code", class: "w-1/2 mr-2" %>
        <%= f.text_field :fa_table_division_season, placeholder: "Division Season", class: "w-1/2" %>
      </div>
    </div>

    <div class="my-3 flex flex-col">
      <%= f.label :fa_table_lrcode, "Fixtures LR Code / Division Season", class: "uppercase text-xs font-light mb-1" %>
      <div class="flex flex-row">
        <%= f.text_field :fa_fixture_lrcode, placeholder: "LR Code", class: "w-1/2 mr-2" %>
        <%= f.text_field :fa_fixture_division_season, placeholder: "Division Season", class: "w-1/2" %>
      </div>
    </div>

  </div>
</div>

<div class="mt-5 flex flex-col">
  <%= f.label :players_as_paragraph, "Players", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_area :players_as_paragraph, class: "w-full lg:w-1/2 h-96" %>
</div>

<div class="mt-5 flex flex-col">
  <%= f.label :team_photo, "Team Photo", class: "uppercase text-xs font-light mb-1" %>
  <% if @record.team_photo.present? %>
    <div class="avatar">
      <div class="w-32 rounded">
        <%= image_tag @record.team_photo %>
      </div>
    </div>
  <% end %>
  <%= f.file_field :team_photo, class: "file-input w-full lg:w-1/2" %>
</div>

app/views/admin/teams/_row.html.erb
<tr>
  <td><%= row.name %></td>
  <td>
    <%= link_to "Edit", edit_admin_team_path(row), class: "btn btn-primary btn-xs" %>
  </td>
</tr>

app/views/admin/videos/_form.html.erb
<div class="my-3 flex flex-col">
  <%= f.label :name, "Name", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_field :name, class: "w-full lg:w-1/2" %>
</div>

<div class="my-3 flex flex-col w-1/2">
  <%= f.label :description, "Description", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_area :description, class: "w-full h-32" %>
</div>

<div class="my-3 flex flex-col">
  <%= f.label :url, "YouTube Url", class: "uppercase text-xs font-light mb-1" %>
  <%= f.text_field :youtube_url, class: "w-full lg:w-1/2" %>
  <p class="text-gray-600 text-xs font-light mt-1">e.g. https://www.youtube.com/watch?v=1KdT8t6M4E4</p>
</div>

app/views/admin/videos/_header.html.erb
<th>Name</th>
<th>Actions</th>

app/views/admin/videos/_row.html.erb
<tr>
  <td><%= row.name %></td>
  <td>
    <%= link_to "Edit", edit_admin_video_path(row), class: "btn btn-primary btn-xs" %>
  </td>
</tr>

app/views/application/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info shadow-lg mb-6">
    <div>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current flex-shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
      <span><%= flash[:notice] %></span>
    </div>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning shadow-lg mb-6">
    <div>
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
      <span><%= flash[:alert] %></span>
    </div>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-error shadow-lg mb-6">
    <div>
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <span><%= flash[:error] %></span>
    </div>
  </div>
<% end %>

app/views/auth0/login.html.erb
<div class="hero bg-base-200 p-24">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-5xl font-bold mb-6">Welcome</h1>
      <%= button_to 'Login', '/auth/auth0', method: :post, data: { turbo: false }, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="bumblebee">
  <head>
    <title>CcfcejaAdmin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div class="navbar bg-[#69132D] text-[#C49A6D]">
        <div class="navbar-start">
          <div class="dropdown">
            <label for="primary-nav-bar" class="md-hide btn-ghost btn-circle btn lg:hidden">
              <svg
              class="swap-off fill-current"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 512 512"
            >
                <path d="M64,384H448V341.33H64Zm0-106.67H448V234.67H64ZM64,128v42.67H448V128Z" />
              </svg>
            </label>
          </div>
        </div>
        <div class="navbar-center">
          <a class="btn-ghost btn text-xl normal-case">CCFC EJA Admin</a>
        </div>
        <% if @user %>
          <div class="navbar-end">
            <div class="dropdown dropdown-end">
              <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                <div class="w-10 rounded-full bg-slate-50">
                  <img src="<%= @user["picture"] %>" />
                </div>
              </label>
              <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-gray-200 text-gray-900 rounded-box w-52">
                <li>
                  <p>
                    Logged in as <b><%= @user["nickname"] %></b>
                  </p>
                </li>
                <li>
                  <%= link_to 'Logout', '/auth/logout', method: :get, data: { turbo: false } %>
                </li>
              </ul>
            </div>
          <% end %>

        </div>
      </div>

      <div class="drawer drawer-mobile">
        <input id="primary-nav-bar" type="checkbox" class="drawer-toggle" />
        <div class="drawer-content flex flex-col p-6">
          <!-- Page content here -->
          <%= render partial: "flash" %>
          <%= yield %>
        </div>

        <% if @user %>
          <div class="drawer-side">
            <label for="primary-nav-bar" class="drawer-overlay"></label>
            <ul class="menu w-80 bg-slate-200 p-4 text-base-content">
              <!-- Sidebar content here -->
              <li>
                <%= link_to "News Articles", admin_news_articles_path %>
              </li>
              <li>
                <%= link_to "Teams", admin_teams_path %>
              </li>
              <li>
                <%= link_to "Sponsors", admin_sponsors_path %>
              </li>
              <li>
                <%= link_to "Videos", admin_videos_path %>
              </li>
              <li>
                <%= button_to 'Publish Site', admin_publications_path, method: :post, data: { turbo: false }, class: "btn btn-primary" %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </header>
  </body>
</html>